pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["()(expressiongroup).htm","(...) （表达式分组）","(...) (表达式分组) Top Previous Next 和在算术中一样，在正则表达式中括号也用于分组。它们经常和 &#39;|&#39; 或 功能一起使用，将多个可选分为一组。 例如： 表达式 &#39;12 Mar(ch)? 2000&#39; 将找到字符串 &#39;12 March 2000&#39; 和 &#39;12 Mar 2...",""],
["(endofstring).htm","$ （字符串的结束）","$ (字符串的结束) Top Previous Next 匹配一个字符串的结尾（要匹配一个字符串的开始，请使用 &#39;^&#39; ）。 例如： 如果您将表达式 &#39;complaint\\.doc$&#39; 作为文件名称输入，那么它将找到以 &#39;complaint.doc&#39; 结尾的所有文件（注意这里对 &#39;.&#39; 使用...",""],
["(escapecharacter).htm","\\ （转义字符）","\\ （转义字符） Top Previous Next 用转义字符抑制其它特殊字符的特殊含义。 例如： 表达式 &#39;Cost$&#39; 将匹配以&#39;Cost&#39;结尾的字符串，而表达式 &#39;Cost\\$&#39; 将匹配含有 &#39;Cost\\$&#39; 的字符串。正如您所看到的一样，转义符抑制了 &#39;$&#39; 字符串的结束 字符的特...",""],
["(expressionor).htm","| （表达式 或）","| (表达式 或) Top Previous Next 当一个表达式或者另一个表达式可以匹配时就使用 | 。 例如： 表达式 &#39;(stabilised|stabilized) condition&#39; 和 &#39;stabili(z|s)ed condition&#39; 都可以匹配上 &#39;stabilised...",""],
["(occurrencecharacters).htm","*, ?, + （次数字符）","*, ?, + （次数字符） Top Previous Next 指定前字符或分组的出现次数。在一个正则表达式中要指定正则表达式应该匹配多少次数时，有四个选择值： 0或1次，字符 ’?&#39; 。 0或多次，字符’*&#39; 。 1或多次，字符&#39;+&#39; 。 仅为1次，字符本身，后面不接任何次数字符。 例如...",""],
["advancedsettings.htm","高级设置","高级设置 Top Previous Next 高级设置分为以下配置组： 文件列表 文件夹 交接点 线程/优先级 XSLT 处理器 Copyright 2013 Mythicsoft Ltd. All rights reserved. Help file version: 7.0 PDF an...",""],
["advanced_criteria.htm","高级界面","高级界面 Top Previous Next 选中&#8220;专家用户&#8221;后条件部分当如图所示： 文件名称 文件名筛选器，如： *.doc;*.txt;*.xls 使用默认的 DOS表达式 来搜索所有doc，txt和xls类型文件。 等效的正则表达式为 \\.(doc|txt|xls)$ 要排除一群文件，...",""],
["advanced_features.htm","高级功能","高级功能 Top Previous Next 更多有关高级功能的信息： 命令行 表达式类型 布尔表达式 DOS表达式 脚本 查找位置 持久性搜索筛选器 Unicode支持 搜索结果内搜索 Outlook PST 归档搜索 MSG文件搜索 Copyright 2013 Mythicsoft L...",""],
["and(characterlists).htm","[...] （字符列表）","[...] （字符列表） Top Previous Next 指定了在字符串中为有效字符的一个列表。可以单独将字符列出来，或者通过用两个字符，然后用’-‘号将它们分隔的方式，来表明一个字符的范围。例如：&#39;[abc]&#39; 将匹配 &#39;a&#39;，&#39;b&#39; 或 &#39;c&#39; 中的任何一个字符。这和 &#39;[a-c]&#39;...",""],
["attributes_tab.htm","属性页签","属性页签 Top Previous Next 属性页签允许根据文件/文件夹的属性对其进行过滤。 每个属性可为以下三个值之一： -- 忽略此属性。 开 文件/文件夹上此属性必须为开。 关 文件/文件夹上此属性必须不能为开。 Copyright 2013 Mythicsoft Ltd. All ...",""],
["basic_interface.htm","基本界面","基本界面 Top Previous Next 未选中&#8220;专家用户&#8221;时，条件部分看上去更像是老式的经典Windows查找工具： : 主要功能： 从&#8220;主要&#8221;页签您可对文件名称、包含文本和查找位置输入框随意输入值，或从过去使用的搜索条件中进行选择（注：仅保留了最后20个条件值）。 此界面同Windo...",""],
["boolean_expressions.htm","布尔表达式","布尔表达式 Top Previous Next 通过使用AND、OR、NOT、NEAR、REGEX及LIKE 操作符，FileLocator Pro的布尔表达式引擎支持网页式的搜索表达式。在 选项页签 中可以将FileLocator Pro设置为对整个文件匹配（默认）或者对逐行匹配。 逐行 ...",""],
["boolean_expressions_settings.htm","布尔表达式设置","布尔表达式设置 Top Previous Next 布尔表达式设置用于控制运算符LIKE和NEAR的行为。 相似灵敏度 在用搜索词匹配相似的单词时，可以设置LIKE运算符来获得不同的灵敏度。可能的设置值有： 非常相似 只接受词语上存在细微的差别，如：一个字符位置不同。 类似 将匹配更广范围的...",""],
["cache_settings.htm","缓存设置","缓存设置 Top Previous Next 缓存设置对话框从 选项页签 中打开。 缓存用于保留从已处理文档文件中提取的文本，即不将非处理类文件的文本进行缓存，如文本文件。对话框中显示了缓存信息、对单个文档的最大缓存允许值以及每个文档的过期策略。 文档最大缓存大小与提取的文本大小有关，与原始...",""],
["character_processing_settings.htm","字符处理设置","字符处理设置 Top Previous Next 字符处理设置控制FileLocator Pro如何处理文件中找到的信息。 行终止(EOL)标识符 定义了FileLocator Pro还要使用哪些其它的行终止标识符。一般情况下，Windows文本文件使用CRLF（回车0x0d，换行符0x0a...",""],
["commandline.htm","命令行","命令行 Top Previous Next FileLocator Pro的启动初值可以通过由命令行传递的信息来改变。如果指定了输出文件，那么就不会显示用户界面，而是将结果直接导入文件中。 可用的命令行选项如下： FileLocatorPro.exe [保存的搜索] | -o [输出文件] ...",""],
["compressed_document_raw_data_r.htm","压缩文档原始数据阅读器","压缩文档原始数据阅读器 Top Previous Next 当某个文档扩展件，如DOC，未被激活时， FileLocator Pro仍然会试图读取文件的原始数据。然而有些文件类型，例如微软Office 2007和Open Office，在存储前使用了ZIP格式对文档数据进行压缩，这就需要Fi...",""],
["configuration2.htm","配置","配置 Top Previous Next FileLocator Pro将所有的配置信息保存在XML文件中，默认情况下位于由 文件夹设置 中定义的 Mythicsoft AppData文件夹中。点击位于工具栏上的&#8220;配置&#8221;按键，或从&#8220;工具&#8221;菜单中选择&#8220;配置...&#8221;选项可以改变配置信息。 配置窗...",""],
["contentsview.htm","内容视图","内容视图 Top Previous Next 在 文件列表视图 中选中的文件都将显示在内容视图中。 摘要页签 摘要页签简单地提供了最近一次搜索的总结： 四个主要数值： 1. 找到项目：.匹配上文件名称及包含文本条件的所有文件总数及总大小。这些文件因此会在 文件列表视图 中列出。 2. 已搜索...",""],
["criteriaview.htm","条件视图","条件视图 Top Previous Next FileLocator Pro提供了两种不同的界面，一种是针对有经验的计算机用户，另一种是针对不希望了解更高级搜索功能的计算机新手。要在两种界面间进行切换，请点选&#8220;专家用户&#8221;复选框。 用户界面: 高级界面 基本界面 保存 FileLocator ...",""],
["datetime_selection.htm","日期/时间 选择","日期/时间 选择 Top Previous Next FileLocator Pro接受各种不同的日期/时间格式来进行基于修改日期/时间的文件过滤。点击上图所示的&#8220;日历&#8221;按键可以指定正确的数值。 日期/时间值属于以下两大类： 固定日期/时间 - 一个在后续搜索中不变的绝对日期/时间值，如：1...",""],
["date_tab.htm","日期页签","日期页签 Top Previous Next 日期页签允许通过最后修改、创建和最后访问日期进行搜索。 点击日历按键将打开 日期/时间 选择对话框 。 注：对条件\"修改日期&#8220;的任何变动都会立即反映在 主要页签 上。 Copyright 2013 Mythicsoft Ltd. All righ...",""],
["display_settings.htm","显示设置","显示设置 Top Previous Next 显示设置控制FileLocator Pro如何显示结果。 显示行 每个文件最大显示行数 限制每个文件返回行的数目，避免对非常大的文件进行无目的搜索，消耗过多的内存。默认值为10000行。 将每行显示的字符最大数限定为 选中时，限制在&#8220;内容视图&#8221;中...",""],
["document_search_settings.htm","文档搜索设置","文档搜索设置 Top Previous Next 文档搜索设置从 选项页签 中打开。 注：实际列出的扩展将取决于每台计算机的设置。 列表中显示了已注册的处理扩展插件（专为帮助搜索程序处理格式而设计的扩展插件）的文件格式。当启用&#8221;深度搜索&#8220;或某些具体扩展插件，FileLocator Pro在搜...",""],
["dos_expressions.htm","DOS表达式设置","DOS 表达式设置 Top Previous Next DOS 表达式设置指定DOS表达式匹配规则是否遵循严格的DOS匹配规则。 在设置为&#8220;严格符合语法&#8221;时，如果发现有通配符，那么DOS匹配规则将在表达式首部和尾部强制进行边界检查，如： 表达式 locator* 不会匹配文件名fileloc...",""],
["dos_expressions2.htm","DOS表达式","DOS表达式 Top Previous Next DOS表达式使用类似的通配符 * 和 ? 指定某一组文件，如：*.pdf 指定了一组具有PDF文件扩展名的文件。然而，FileLocator Pro 还用另一些特殊字符扩充了DOS表达式的功能。 字符 描述 示例 * 匹配零个或多个字符 To...",""],
["editor.htm","编辑器设置","编辑器设置 Top Previous Next 默认编辑器 默认情况下FileLocator Pro用其内嵌文件查看器显示某文件内容的只读视图。然而可以通过指定参数地址名称和命令行将默认查看器更改为一个外部第三方编辑器。FileLocator Pro还支持使用微软的Visual Studio...",""],
["expressiontypes.htm","表达式类型","表达式类型 Top Previous Next FileLocator 支持以下的表达式类型： 布尔 布尔正则表达式 全字匹配 DOS 精确匹配 正则表达式 文件哈希值 布尔表达式 布尔表达式用AND、OR、NOT、LIKE及NEAR操作符将单个的搜索词组连在一起。更多信息，请参见 布尔表达...",""],
["expressionwizard(exprwiz).htm","表达式向导","表达式向导 Top Previous Next 表达式向导逐步向用户演示建立一个基本的 正则表达式 。可以用表达式向导来创建文件名称或文件内容搜索的表达式。 注：术语&#8221;字符串&#8220;是一个用作指文件名或文件内容的通用术语。基本上说字符串是任何单词或单词组，若您想一想，那不就是文件名么。 首页（介绍...",""],
["expression_settings.htm","表达式设置","表达式设置 Top Previous Next 表达式设置控制了FileLocator Pro的每个表达式引擎的各种匹配规则。本部分又分为： 布尔表达式设置 DOS表达式设置 正则表达式设置 文件哈希值设置 Copyright 2013 Mythicsoft Ltd. All rights ...",""],
["extensions2.htm","扩展件","扩展件 Top Previous Next 默认情况下FileLocator Pro以文件的原始二进制格式打开文件。虽然这对文本格式非常奏效，然而其它文件，例如：ZIP文件或微软Office 2010文件却没有那么理想。扩展件可以帮助FileLocator Pro处理非文本格式的文件从而正确...",""],
["extension_tab.htm","压缩文件页签","压缩文件页签 Top Previous Next 压缩文件页签显示了和压缩/归档格式有关的扩展名列表。 当启用了一种压缩文件格式，FileLocator Pro将把找到的任何该类型的文件作为文件系统中文件夹层次中的一部分，例如： c:\\zips\\file1.zip\\compressed\\do...",""],
["favorites.htm","收藏","收藏 Top Previous Next 可以将要频繁执行的搜索保存为&#8220;收藏&#8221;。&#8220;收藏&#8221;是指可以很快载入搜索面板的的已保存的搜索，用于在不同搜索类别间方便地切换。 要使用&#8220;收藏&#8221;功能，点击工具栏的&#8220;收藏&#8221;按钮（或按Ctrl+D）： 将打开收藏面板并显示过去保存的搜索收藏。 添加一个收藏 要添...",""],
["filelistview.htm","文件列表视图","文件列表视图 Top Previous Next 在搜索时当找到了文件，它们将出现在&#8221;文件列表视图&#8220;中。将分别显示出每个文件的名称和位置。在这个视图中选择的文件将出现在 内容视图 中。 FileLocator Pro支持上下文菜单，能列出对选中的一个文件或一群的文件可进行的有效操作。上下文菜...",""],
["file_hash_settings.htm","文件哈希值设置","文件哈希值设置 Top Previous Next 文件哈希值设置指定在搜索某个文件哈希值时FileLocator使用哪些哈希值算法。 Copyright 2013 Mythicsoft Ltd. All rights reserved. Help file version: 7.0 PDF...",""],
["file_lists.htm","文件列表","文件列表 Top Previous Next 文件列表表明条件值是否能从文本中加载。 例子：文件名列表 如果&#8220;文件名称&#8221;条件允许使用文件列表（默认的设置），那么不用指定： *.c;*.cpp;*.h;*.hpp;*.inl;*.res;*.rc 用户而是可以指定： =C:\\FileLists...",""],
["folder_settings.htm","文件夹设置","文件夹设置 Top Previous Next 文件夹设置指定FileLocator Pro保存其配置、日志及收藏文件所用的位置。 默认位置为： $(ApplicationData)\\logs\\ $(ApplicationData)\\config\\ $(ApplicationData)\\Fa...",""],
["generalsettings.htm","常规设置","常规设置 Top Previous Next 常规设置分为以下配置组： 历史 显示 搜索 字符处理 外壳程序集成 声音/警告 本地化 用户界面 Copyright 2013 Mythicsoft Ltd. All rights reserved. Help file version: 7.0...",""],
["gettingstarted.htm","开始使用","开始使用 Top Previous Next 当您开始使用 FileLocator Pro，它大体应该如下图所示: 软件界面分为三个主要部分: 条件视图 , 用于输入搜索条件. 如果选中&#8220;专家用户&#8221;(默认)，您将看到 高级界面 ，否则将看到 基本界面。 文件列表视图 , 显示搜索中找到的文件...",""],
["hintstips.htm","提示","提示 Top Previous Next 搜索多个文件类型 您能用正则表达式或DOS表达式搜索多种类型的文件，如： 搜索.ccp，.cpp，.h，.c，.INL，那么正则表达式就为： \\.(cpp|h|c|INL)$ 或者，可以用DOS表达式，那么就是： *.cpp;*.h;*.c;*.IN...",""],
["history.htm","历史设置","历史设置 Top Previous Next 历史设置控制 FileLocator Pro对过去的搜索记住哪些信息。 要清空当前历史，点击&#8220;清除历史记录...\"按键。要在每次FileLocator Pro程序退出时清空历史记录，选中&#8220;退出时清除所有历史记录&#8221;。 记忆 选项设置 当选中后，Fi...",""],
["ifilters.htm","IFilters","IFilters Top Previous Next 微软索引服务（Microsoft Indexing Service）使用了和FileLocator Pro扩展件很相似的筛选器，将指定文件类型解释成为易于搜索的文本。FileLocator Pro可以用这些索引服务筛选器帮助将文件转换为易...",""],
["internal_file_viewer.htm","内部文件查看器","内部文件查看器 Top Previous Next 内部查看器对找到的文件提供了一个只读的呈现界面，且以高亮显示出匹配项。 二级搜索 在&#8220;查找&#8221;编辑框中输入文本然后按回车可对此文件进行另外的搜索。 定位条 提供显示在文件内容中的行相对于文件其余部分的一个位置纵览。 文件内容 显示从内容视图中...",""],
["introduction.htm","介绍","介绍 Top Next 欢迎使用 FileLocator Pro FileLocator Pro 是由Mythicsoft公司制作的一款获奖文件搜索软件。 FileLocator Pro 提供了一套全面的功能来帮助您查找您计算机上的文件，了解您计算机中的信息。 接下来做什么呢? 请查阅\"开始...",""],
["junction_points.htm","交接点","交接点 Top Previous Next NTFS交接点是指在系统中对其它文件夹的链接。它们类似于符号链接，只不过更强，即针对大多数的目的和用途来说，引用某个交接点和引用文件夹是一样的。 默认情况下FileLocator Pro会搜素除有&#8221;系统&#8220;和&#8220;隐藏&#8221;（一般表明这是系统交接点）属性之外...",""],
["localization_settings.htm","本地化设置","本地化设置 Top Previous Next 本地化设置指定对用户界面用哪种语言。 Copyright 2013 Mythicsoft Ltd. All rights reserved. Help file version: 7.0 PDF and CHM versions of this...",""],
["look_in.htm","Look In","查找位置 Top Previous Next 经常在\"查找位置&#8221;输入框中只会指定单个的文件夹位置来进行搜索。然而，&#8220;查找位置&#8221;输入框内可接受的远不止单个文件夹位置。 &#8220;查找位置&#8220;输入框接受的值类型有： 单个文件夹 如：c:\\work\\doc 表达式 可对文件夹路径中的部分来指定表达式，即，表...",""],
["memory_manager_settings.htm","内存管理设置","内存管理设置 Top Previous Next 如果FileLocator Pro检测到正在消耗大量的内存，它便能截短搜索结果以减少所需的内存数量。内存管理设置允许您自定义截断的位置，或是完全关闭此项功能。 Copyright 2013 Mythicsoft Ltd. All rights...",""],
["msg_file_searching.htm","MSG文件搜索","MSG文件搜索 Top Previous Next MSG文件搜索是通过&#8221;选项\"页签激活的。 当激活后，FileLocator Pro会将MSG文件作为其它文件的容器，即，MST文件成为了&#8220;虚拟&#8221;文件夹。将一个电子邮件文本主体作为一个.txt文件，将每个电子邮件附件作为单独文件（假设选中&#8220;搜...",""],
["options_advanced.htm","选项页签","选项页签 Top Previous Next 布尔表达式 布尔表达式搜索类型定义表达式是按照逐行还是在整个文件范围内进行匹配。 例如：&#8220;File And Pro\"根据逐行匹配将找出仅包含有&#8221;File\"和&#8220;Pro\"的行，因此找出仅有至少有一行同时含&#8221;File\"和\"Pro\"的文件。如果按照整个文...",""],
["otherexamples.htm","其它示例","其它示例 Top Previous AND 与 虽然正则表达式引擎没有直接支持布尔AND运算，但是能以有限的方式对它进行模拟。 例如： 要搜索包含有 &#39;error&#39; 与 &#39;log&#39; 的行，正则表达式将为 &#39;(error.*log)|(log.*error)&#39; 。基本上是将不同可能的组合进行了...",""],
["other_extensions.htm","FileLocator Pro 扩展件","FileLocator Pro 扩展件 Top Previous Next 扩展见帮助FileLocator对非文本格式进行处理，从而来正确地获取和搜索它们的内部数据。 此屏幕截图显示出ZIP扩展件的配置。ZIP扩展件用于读取ZIP格式的文件。配置中显示出ZIP扩展件应当用于所有拥有.zip...",""],
["outlook_pst_archive_searching.htm","Outlook PST 归档搜索","Outlook PST 归档搜索 Top Previous Next FileLocator Pro能够搜索从较早的Outlook 97一直到最新版本的Outlook的所有PST归档。同样是由于FileLocator Pro‘理解’实际的内部格式，从而不需要安装Outlook，还可以越过PS...",""],
["persistent_search_filters.htm","持久性搜索筛选器","持久性搜索筛选器 Top Previous Next 经常将 位置筛选器 用于包含或排除一个搜索的某些搜索位置。有一些筛选器很常见，每次搜索都要用它们，如：排除源代码元数据文件夹。持久性搜索筛选器可以为这样的（启用时）对所有搜索都适用的普遍搜索筛选器进行定义。 当启用了一个或多个持久性搜索筛...",""],
["questionscomments.htm","问题/评价","问题/评价 Top Previous Next 在Mythicsoft的知识库中有更多信息： http://www.mythicsoft.com/kb http://qa.mythicsoft.com/ 有任何的问题或看法，欢迎您和我们取得联系： http://www.mythicsoft....",""],
["quickstart.htm","快速入门","快速入门 Top Previous Next FileLocator Pro 将正则表达式引擎作为 表达式类型 中的一种。正则表达式（有时简称为正则表达）提供了一种可以精确地描述要搜索什么的简明的语言。用非常基础的语言，您能将一个表达式分为两部分： - 您正在要寻找什么。 - 您希望查找它出...",""],
["regularexpressionbasics.htm","正则表达式基础知识","正则表达式基础知识 Top Previous Next 正则表达式使用特殊的字符（也叫做正则表达式运算符）来指定字符串的规则。对这些字符的总结可为： ^ 字符串的开始 $ 字符串的结束 . 任何单个字符 [ 字符列表的开始 ] 字符列表的结束 ( 表达式分组的开始 ) 表达式分组的结束 | ...",""],
["regularexpressionintroduction.htm","什么是正则表达式？","什么是正则表达式? Top Previous Next 正则表达式是一种用来描述一群单词（称作‘字符串’）的方法。它允许使用者建立一套复杂的规则来精确描述要字符串具备的特征。虽然本文档中使用了词语‘字符串’，不过您可以在用正则表达式搜索文件名时将字符串作为文件名，或者在用正则表达式搜索文件内...",""],
["regular_expressions.htm","正则表达式","正则表达式 Top Previous Next FileLocator Pro用Perl兼容语法或经典语法提供了对正则表达式广泛的支持。 Perl兼容语法 Perl兼容正则表达式语法基于Boost正则表达式引擎，它不仅包含&#8220;经典&#8221;正则表达式引擎的功能，还有包含了具有Perl风格的表达式增强部...",""],
["regular_expression_settings.htm","正规表达式设置","正则表达式设置 Top Previous Next 正则表达式设置定义了搜索时使用的正则表达式的语法。可以是与Perl语言兼容的正则表达式语法，或者是经典正则表达式的语法。更多信息，请参见 表达式类型 。 往往&#8221;使用多个校对规则&#8220;在搜索外文文本时十分有用。它可以将标准的[a-z]字母范围外的...",""],
["reports.htm","Reports","报告 Top Previous Next FileLocator Pro的报告功能提供了一个迅速的方法导出，打印搜索结果信息和生成信息摘要。有四个主要的报告：文件列表报告，内容报告，关键词摘要报告和关键词按文件报告。所有报告都可以用自定义包含/排除不同的部分和列。 文件列表报告 文件列表报告...",""],
["save_results.htm","导出结果","导出结果 Top Previous Next FileLocator Pro为导出结果提供了 报告 功能以及文件 - 导出结果的菜单选项。&#8220;导出结果&#8221;对话框可将结果保存至剪贴板上，或一个指定文件中。 结果可以用各种格式来保存： 以逗号分隔（CSV) 以逗号分隔的查找结果表格（为后续在EXCE...",""],
["scripting.htm","脚本","脚本 Top Previous Next FileLocator Pro 支持使用活动脚本来定制搜索引擎的文件名称和内容的匹配算法。 当用户启动一次搜索，FileLocator Pro将： 了解是否可有脚本启用。 根据&#8220;引擎&#8221;输入框内输入的程序号（Prog Id）对每个脚本创建活动脚本引擎。...",""],
["scriptin_tab.htm","脚本页签","脚本页签 Top Previous Next 脚本允许通过用任何有效活动脚本对搜索引擎的&#8221;文件名称&#8220;和&#8221;内容&#8221;匹配算法进行自定义。 可以指定某脚本文件作为对文件名称匹配时的规则或对包含文本匹配时的规则。 将&#8220;引擎&#8221;的值设置为将要用来执行脚本的相应的活动脚本引擎程序ID号。在下拉菜单下列出了两...",""],
["searchwizard.htm","搜索向导","搜索向导 Top Previous Next 搜索向导用例子和性能提示向用户逐步演示如何输入基本搜索条件。 向用户呈现了三个页面，询问接下来的信息： 文件名称 文件内容 文件位置 在最后一页，如果选中了复选框&#8221;自动开始搜索&#8220;，那么用户点击&#8221;完成&#8220;按键后搜索将开始进行。 Copyright 2...",""],
["search_navigation.htm","搜索导航","搜索导航 Top Previous Next 使用搜索导航可以浏览与/或重用从前的搜索。和浏览器上的前进和后退按键十分相似，搜索导航按键可前后浏览各个搜索。 可浏览的搜索数是由 历史设置 中的&#8221;搜索导航&#8220;的设置决定的。 Copyright 2013 Mythicsoft Ltd. All r...",""],
["search_settings.htm","搜索设置","搜索设置 Top Previous Next 搜索设置定义了FileLocator Pro如何搜索文件。 默认情况下FileLocator Pro按照多个阶段搜索文件。首先，它收集在&#8221;文件名称\"条件中指定的文件的相关信息，然后在第二阶段，重新开始对这些文件进行搜索。如此可以使FileLoca...",""],
["search_within_search.htm","搜索结果内搜索","搜索结果内搜索 Top Previous Next 有时候更加希望将后续搜索的范围限制在结果列表或结果列表的一个子集。通过两个菜单选项，FileLocator Pro支持对文件子集的搜索。 文件 - 搜索结果列表 搜索在结果列表中列出的所有文件。 文件 - 搜索当前所选内容 搜索在结果列表中...",""],
["sessions_and_workspaces.htm","会话，工作区及搜索条件","会话，工作区及搜索条件 Top Previous Next FileLocator Pro允许搜索数据以很多不同的方式导出，可是虽然 导出结果 和 报告 功能在用于普通格式的导出上很有用，例如：文本，CSV和HTML格式，但它们都无法用来把搜索数据再次加载到程序中。为此FileLocator...",""],
["shell_integration_settings.htm","外壳程序集成","外壳程序集成 Top Previous Next 外壳程序集成设置控制了FileLocator Pro如何集成到Window外壳程序中。 与SRF文件类型关联 将FileLocator Pro与扩展名SRF关联。SRF是 FileLocator Pro保存结果文件的默认扩展名。设置后，双击一...",""],
["soundsalerts_settings.htm","声音/警告设置","声音/警告设置 Top Previous Next 声音和警告配置以可选项方式，针对不同FileLocator Pro事件提供了另外视觉上的或声音的提醒。 文件找到 播放声音 指定如果找到了一个文件所播放的波形文件。 显示任务栏通知消息 指定当找到了一个文件时是否要在任务栏显示一个通知窗口，...",""],
["threadspriority_settings.htm","线程/优先级设置","线程/优先级设置 Top Previous Next 线程/优先级设置影响到 FileLocator Pro如何利用CPU。 并发线程数 默认情况下FileLocator Pro对每个CPU核心使用单个线程来搜索文件，这样的配置通常是最为有效的。然而，可以取消&#8220;自动管理&#8221;选项指定进程数来指定...",""],
["unicode_support.htm","Unicode支持","Unicode支持 Top Previous Next 文件系统的Unicode支持 FileLocator Pro是以Windows Unicode 程序库建立起的，因此对文件系统搜索提供了完整的Unicode支持。 内容搜索的Unicode支持 经过扩展件（如：IFilters）处理的文...",""],
["user_interface_settings.htm","用户界面设置","用户界面设置 Top Previous Next 用户界面设置控制了FileLocator Pro的&#8220;外观和感觉&#8221;。 默认 将FileLocator Pro配置为采用&#8220;标准主题&#8221;及选项卡式用户界面。 经典 将FileLocator Pro配置为在外观和行为上与FileLocator Pro ...",""],
["utf_8_default_format.htm","UTF-8 默认格式","UTF-8 默认格式 Top Previous Next 如果FileLocator Pro无法（通过BOM 或 XML头信息）检测一个文件的编码，那么就会试图以ASCII文本读取此文件。然而可以覆盖此行为，将给定文件类型的默认格式指定为 UTF-8。 Copyright 2013 Myth...",""],
["wizards.htm","Wizards","向导 Top Previous Next 为了帮助用户使用FileLocator Pro软件的复杂功能，提供了两个向导： 搜索向导 （只在基础界面中） 表达式向导 （只在高级界面中） Copyright 2013 Mythicsoft Ltd. All rights reserved. He...",""],
["xslt_processor_settings.htm","XSLT处理器设置","XSLT处理器设置 Top Previous Next 保存结果 提供了一个选项运行一个XSL转换文件，提供自定义的格式化处理。FileLocator Pro使用微软XML核心服务（MS XML Core Services）来提供此转换功能，但是实际的DOM 程序 Id可在此配置： Copy...",""],
["%5E(beginningofstring).htm","^ （字符串的开始）","^ （字符串的开始） Top Previous Next 匹配一个字符串的开始（要匹配一个字符串的结束，请使用 &#39;$&#39; ）。 例如： 如果您将表达式 &#39;^win&#39; 作为文件名称输入，那么它将找到以 &#39;win&#39; 开始的所有文件。因此它将找到如 &#39;winhelp.exe&#39; 和 &#39;windows_...",""]];
