pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["()(expressiongroup).htm","(...) (Expression group)","(...) (Expression group) Top Previous Next Parentheses are used for grouping in regular expressions as in arithmetic. They are often used with the...",""],
["(endofstring).htm","$ (End of string)","$ (End of string) Top Previous Next Matches the end of a string (to match the beginning of a string use &#39;^&#39; ). For example: If you entered the fil...",""],
["(escapecharacter).htm","\\ (Escape character)","\\ (Escape character) Top Previous Next Escape character is used to suppress the special meaning of other special characters. For example: The expr...",""],
["(expressionor).htm","| (Expression OR)","| (Expression OR) Top Previous Next Use the | when either one expression or another will do. For example: Both the expressions &#39;(stabilised|stabil...",""],
["(occurrencecharacters).htm","*, ?, + (Occurrence characters)","*, ?, + (Occurrence characters) Top Previous Next Specifies the number of occurrences of the preceding character or group. In a regular expression...",""],
["advancedsettings.htm","Advanced Settings","Advanced Settings Top Previous Next Advanced settings are broken up into the following configuration groups: File Lists Folders Junction Points Th...",""],
["advanced_criteria.htm","Advanced Interface","Advanced Interface Top Previous Next With Expert User checked the criteria section should look like this: File name File name filter, e.g. *.doc;*...",""],
["advanced_features.htm","Advanced features","Advanced features Top Previous Next More information on advanced features: Command line Expression types Boolean Expressions Scripting Look In Per...",""],
["and(characterlists).htm","[...] (Character lists)","[...] (Character lists) Top Previous Next Specifies a list of characters that are valid in the string. Characters can be listed individually or a ...",""],
["attributes_tab.htm","Attributes tab","Attributes tab Top Previous Next The attributes tab allows filtering of files/folders based on their attributes. Each attribute can be one of thre...",""],
["basic_interface.htm","Basic Interface","Basic Interface Top Previous Next With Expert User unchecked the criteria section looks more like the old classic Windows Find tool: Main features...",""],
["boolean_expressions.htm","Boolean Expressions","Boolean Expressions Top Previous Next FileLocator Pro&#39;s Boolean expression engine supports Web style search expressions using the AND, OR, NOT, NE...",""],
["boolean_expressions_settings.htm","Boolean Expression Settings","Boolean Expression Settings Top Previous Next Boolean expression settings are used to control how the operators LIKE and NEAR behave. LIKE Sensiti...",""],
["cache_settings.htm","Cache Settings","Cache Settings Top Previous Next The Cache Settings dialog is opened from the Options tab . The cache is used to retain text extracted from proces...",""],
["character_processing_settings.htm","Character Processing Settings","Character Processing Settings Top Previous Next Character processing settings control how FileLocator Pro handles information found in files. End ...",""],
["commandline.htm","Command Line","Command Line Top Previous Next FileLocator Pro&#39;s start up values can be altered through information passed through the command line. If an output ...",""],
["compressed_document_raw_data_r.htm","Compressed Document Raw Data Reader","Compressed Document Raw Data Reader Top Previous Next When a document extension, such as DOC, is not active FileLocator Pro still tries to read th...",""],
["configuration2.htm","Configuration","Configuration Top Previous Next FileLocator Pro stores all its configuration information in XML files located, by default, in the Mythicsoft AppDa...",""],
["contentsview.htm","Contents View","Contents View Top Previous Next Any files selected in the File List view are displayed in the Contents view. Summary Tab The summary tab simply pr...",""],
["criteriaview.htm","Criteria View","Criteria View Top Previous Next FileLocator Pro provides two different interfaces, one for the experienced computer user, and the other for the no...",""],
["datetime_selection.htm","Date/Time Selection","Date/Time Selection Top Previous Next FileLocator Pro accepts various different date/time formats for filtering files based on the modified date/t...",""],
["date_tab.htm","Date tab","Date tab Top Previous Next The date tab allows searching by last modified, created, and last accessed date. Clicking the calendar buttons will ope...",""],
["display_settings.htm","Display Settings","Display Settings Top Previous Next Display settings control how FileLocator Pro displays results. Display Lines Max displayed lines per file Limit...",""],
["document_search_settings.htm","Document Search Settings","Document Search Settings Top Previous Next The Document Search Settings is opened from the Options tab . Note: The actual extensions listed will d...",""],
["dos_expressions.htm","DOS Expression Settings","DOS Expression Settings Top Previous Next DOS expression settings specify whether the DOS expression matching rules will follow strict DOS matchin...",""],
["dos_expressions2.htm","DOS Expressions","DOS Expressions Top Previous Next DOS Expressions use the familiar wildcards * and ? to specify groups of files, e.g. *.pdf to specify a group of ...",""],
["editor.htm","Editor Settings","Editor Settings Top Previous Next Default Editor FileLocator Pro by default uses its built-in file viewer to display a read-only view of a file&#39;s ...",""],
["expressiontypes.htm","Expression Types","Expression Types Top Previous Next FileLocator supports the following expression types: Boolean Boolean RegEx Whole Word DOS Exact match Regular e...",""],
["expressionwizard(exprwiz).htm","Expression Wizard (Expr Wiz)","Expression Wizard (Expr Wiz) Top Previous Next Expression Wizard walks the user through creating a basic regular expression . The Expression Wizar...",""],
["expression_settings.htm","Expression Settings","Expression Settings Top Previous Next Expression settings control the various matching rules for each of FileLocator Pro&#39;s expression engines. Thi...",""],
["extensions2.htm","Extensions","Extensions Top Previous Next By default FileLocator Pro opens files in their raw binary format. While this works well for text based formats other...",""],
["extension_tab.htm","Compressed Files tab","Compressed Files tab Top Previous Next The Compressed Files tab shows the list of extensions relating to compressed/archive formats. When a compre...",""],
["favorites.htm","Favorites","Favorites Top Previous Next Searches that are performed frequently can be saved as Favorites. Favorites are saved searches that can be quickly loa...",""],
["filelistview.htm","File List View","File List View Top Previous Next As files are found during the search they appear in the File List view. For each file its name and location are d...",""],
["file_hash_settings.htm","File Hash Settings","File Hash Settings Top Previous Next File Hashing Settings specifies which hashing algorithms FileLocator Pro should use when searching for a give...",""],
["file_lists.htm","File Lists","File Lists Top Previous Next File Lists indicate whether or not a criteria value can be loaded from a text file. Example: File name list If the Fi...",""],
["folder_settings.htm","Folder Settings","Folder Settings Top Previous Next Folder Settings specify the location that FileLocator Pro stores its configuration, log, and favorite files. The...",""],
["generalsettings.htm","General Settings","General Settings Top Previous Next General settings are broken up into the following configuration groups: History Display Search Character Proces...",""],
["gettingstarted.htm","Getting started","Getting started Top Previous Next When you start FileLocator Pro it should look something like this: The interface is broken up into three main se...",""],
["hintstips.htm","Hints &#38; Tips","Hints &#38; Tips Top Previous Next Searching for multiple file types You can search multiple files by using regular expressions or DOS expressions. e....",""],
["history.htm","History Settings","History Settings Top Previous Next History settings control which information FileLocator Pro remembers about previous searches. To clear the curr...",""],
["ifilters.htm","IFilters","IFilters Top Previous Next Microsoft Indexing Service uses filters, much like FileLocator Pro extensions, to interpret given file types into easil...",""],
["internal_file_viewer.htm","Internal File Viewer","Internal File Viewer Top Previous Next The Internal Viewer is a read-only display of the found file with the search hits highlighted. Secondary Se...",""],
["introduction.htm","Introduction","Introduction Top Next Welcome to FileLocator Pro FileLocator Pro is the award winning file searching tool from Mythicsoft. FileLocator Pro offers ...",""],
["junction_points.htm","Junction Points","Junction Points Top Previous Next NTFS Junction Points are links to other folders on the system. They are similar to symbolic links only stronger,...",""],
["localization_settings.htm","Localization Settings","Localization Settings Top Previous Next Localization settings specify which language should be used for the user interface. Copyright 2013 Mythics...",""],
["look_in.htm","Look In","Look In Top Previous Next Often the Look In field simply specifies a single folder to search through. However, the Look In field can accept much m...",""],
["memory_manager_settings.htm","Memory Manager Settings","Memory Manager Settings Top Previous Next If FileLocator Pro detects that it&#39;s consuming large amounts of memory it can truncate the search result...",""],
["msg_file_searching.htm","MSG File Searching","MSG File Searching Top Previous Next MSG file searching is activated through the Options tab. When activated FileLocator Pro treats MSG files as c...",""],
["options_advanced.htm","Options tab","Options tab Top Previous Next Boolean Expression Boolean expression search type defines whether Boolean expressions are matched on a line by line ...",""],
["otherexamples.htm","Other Examples","Other Examples Top Previous AND Although the regular expression engine does not directly support the concept of the boolean AND operation it can, ...",""],
["other_extensions.htm","FileLocator Pro Extensions","FileLocator Pro Extensions Top Previous Next Extensions help FileLocator Pro in processing non-text based formats so that their underlying data is...",""],
["outlook_pst_archive_searching.htm","Outlook PST Archive Searching","Outlook PST Archive Searching Top Previous Next FileLocator Pro is able to search through all PST archives from the older Outlook 97 right up to t...",""],
["persistent_search_filters.htm","Persistent Search Filters","Persistent Search Filters Top Previous Next Location filters are often used to include or exclude certain search locations for a given search. Som...",""],
["questionscomments.htm","Questions/Comments ?","Questions/Comments ? Top Previous Next More information is available in the Mythicsoft knowledge base: http://www.mythicsoft.com/kb and the Mythic...",""],
["quickstart.htm","Quick Start","Quick Start Top Previous Next FileLocator Pro includes a regular expression engine as one of its Expression Types . Regular expressions (some time...",""],
["regularexpressionbasics.htm","Regular expression basics","Regular expression basics Top Previous Next Regular expressions use special characters (also known as regular expression operators) to specify rul...",""],
["regularexpressionintroduction.htm","What is a regular expression?","What is a regular expression? Top Previous Next A regular expression is a way of describing a group of words (referred to as a &#39;string&#39;). It allow...",""],
["regular_expressions.htm","Regular Expressions","Regular Expressions Top Previous Next FileLocator Pro provides extensive regular expression support using either a Perl compatible syntax or a cla...",""],
["regular_expression_settings.htm","Regular Expression Settings","Regular Expression Settings Top Previous Next Regular expression settings defines the regex syntax to use when searching. This can either be the P...",""],
["reports.htm","Reports","Reports Top Previous Next FileLocator Pro&#39;s reporting feature provides a quick way to export, print and summarize search information. There are fo...",""],
["save_results.htm","Export Results","Export Results Top Previous Next For exporting results FileLocator Pro provides both the Reports functionality and the File - Export Results menu ...",""],
["scripting.htm","Scripting","Scripting Top Previous Next FileLocator Pro supports Active Scripting to customize the search engine&#39;s file name and contents matching algorithms....",""],
["scriptin_tab.htm","Scripting tab","Scripting tab Top Previous Next Scripting allows customization of the search engine&#39;s file name and contents matching algorithms through any valid...",""],
["searchwizard.htm","Search Wizard","Search Wizard Top Previous Next Search Wizard walks the user through entering the basic search criteria with examples and performance tips. The us...",""],
["search_navigation.htm","Search Navigation","Search Navigation Top Previous Next Using search navigation it is possible to browse and/or reuse previous searches. Much like the forward and bac...",""],
["search_settings.htm","Search Settings","Search Settings Top Previous Next Search settings define how FileLocator Pro searches files. By default FileLocator Pro searches files in multiple...",""],
["search_within_search.htm","Search within Search","Search within Search Top Previous Next Sometimes it is preferable to limit subsequent searches to the result list or a subset of the result list. ...",""],
["sessions_and_workspaces.htm","Sessions, Workspaces and Search Criteria","Sessions, Workspaces and Search Criteria Top Previous Next FileLocator Pro allows search data to be exported in a number of different ways but whi...",""],
["shell_integration_settings.htm","Shell Integration Settings","Shell Integration Settings Top Previous Next Shell integration settings control how FileLocator Pro integrates into the Window shell. Associate wi...",""],
["soundsalerts_settings.htm","Sounds/Alerts Settings","Sounds/Alerts Settings Top Previous Next Sounds and Alerts configuration optionally provides additional visual or audible notifications for differ...",""],
["threadspriority_settings.htm","Threads/Priority Settings","Threads/Priority Settings Top Previous Next Thread/Priority settings effect how FileLocator Pro uses the CPU. Concurrent threads By default FileLo...",""],
["unicode_support.htm","Unicode Support","Unicode Support Top Previous Next File System Unicode Support FileLocator Pro is built with the Windows Unicode libraries and therefore supports s...",""],
["user_interface_settings.htm","User Interface Settings","User Interface Settings Top Previous Next User Interface settings control the FileLocator Pro &#39;Look and Feel&#39;. Default FileLocator Pro is configur...",""],
["utf_8_default_format.htm","UTF-8 Default Format","UTF-8 Default Format Top Previous Next If FileLocator Pro is unable to detect a file&#39;s encoding (through the BOM or XML header) it tries to read t...",""],
["wizards.htm","Wizards","Wizards Top Previous Next To help the user with some of FileLocator Pro&#39;s complex features two wizards are available: Search wizard (Basic interfa...",""],
["xslt_processor_settings.htm","XSLT Processor Settings","XSLT Processor Settings Top Previous Next Save Results provides an option to run an XSL transform to provide custom formatting. FileLocator Pro us...",""],
["%5E(beginningofstring).htm","^ (Beginning of string)","^ (Beginning of string) Top Previous Next Matches the beginning of a string (to match the end of a string use &#39;$&#39; ). For example: If you entered t...",""]];
